name:                bondwb
version:             0.7.0.0
github:              "githubuser/bondwb"
license:             GPL-3
author:              "Thomas Wright, Ian Stark"
maintainer:          "tom.tdw@gmail.com"
copyright:           "2016-2019 Thomas Wright, Ian Stark"
# Metadata used when publishing your package
synopsis:            "The bond-calculus Workbench: An interactive command-line tool for working with the bond-calculus"
category:            SystemsBiology

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bondwb#readme>

# dependencies:
# - base >= 4.7 && < 5
# - bondlib

library:
  source-dirs: .
  dependencies:
    - base
    - sharedlib
    - bondlib
    - scientific
    - megaparsec
  # exposed-modules: BondCalculus.ArgListParser
  # exposed-modules: BondCalculus.ArgListParser

executables:
  bondwb:
    main:                biowb.hs
    # source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - bondwb
    - sharedlib
    - bondlib
    - optparse-applicative
    - haskeline
    - transformers
    - Chart
    # - Chart-gtk
    - containers
    - scientific
    - hashable
    - megaparsec
